# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_example', [dirname(__file__)])
        except ImportError:
            import _example
            return _example
        if fp is not None:
            try:
                _mod = imp.load_module('_example', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _example = swig_import_helper()
    del swig_import_helper
else:
    import _example
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def activate(input, output_shape, type):
    return _example.activate(input, output_shape, type)
activate = _example.activate

def sigmoid(input):
    return _example.sigmoid(input)
sigmoid = _example.sigmoid

def softplus(input):
    return _example.softplus(input)
softplus = _example.softplus

def softsign(input):
    return _example.softsign(input)
softsign = _example.softsign

def hard_sigmoid(input):
    return _example.hard_sigmoid(input)
hard_sigmoid = _example.hard_sigmoid

def exponential(input):
    return _example.exponential(input)
exponential = _example.exponential

def relu(input):
    return _example.relu(input)
relu = _example.relu

def hyper_tan(input):
    return _example.hyper_tan(input)
hyper_tan = _example.hyper_tan

def softmax(input, output_shape):
    return _example.softmax(input, output_shape)
softmax = _example.softmax
# This file is compatible with both classic and new-style classes.

cvar = _example.cvar
conv2d_W = cvar.conv2d_W
conv2d_b = cvar.conv2d_b
dense_W = cvar.dense_W
dense_b = cvar.dense_b
dense_1_W = cvar.dense_1_W
dense_1_b = cvar.dense_1_b

