# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_conv1d', [dirname(__file__)])
        except ImportError:
            import _conv1d
            return _conv1d
        if fp is not None:
            try:
                _mod = imp.load_module('_conv1d', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _conv1d = swig_import_helper()
    del swig_import_helper
else:
    import _conv1d
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def buildConv1D(W, b, kernel_size, strides, input_sh0, input_sh1, filters, activation, padding, data_format, dilation_rate):
    return _conv1d.buildConv1D(W, b, kernel_size, strides, input_sh0, input_sh1, filters, activation, padding, data_format, dilation_rate)
buildConv1D = _conv1d.buildConv1D

def padding_conv1(L, input):
    return _conv1d.padding_conv1(L, input)
padding_conv1 = _conv1d.padding_conv1

def fwdConv1D(L, input):
    return _conv1d.fwdConv1D(L, input)
fwdConv1D = _conv1d.fwdConv1D
class Conv1D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Conv1D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Conv1D, name)
    __repr__ = _swig_repr
    __swig_setmethods__["weights"] = _conv1d.Conv1D_weights_set
    __swig_getmethods__["weights"] = _conv1d.Conv1D_weights_get
    if _newclass:
        weights = _swig_property(_conv1d.Conv1D_weights_get, _conv1d.Conv1D_weights_set)
    __swig_setmethods__["biases"] = _conv1d.Conv1D_biases_set
    __swig_getmethods__["biases"] = _conv1d.Conv1D_biases_get
    if _newclass:
        biases = _swig_property(_conv1d.Conv1D_biases_get, _conv1d.Conv1D_biases_set)
    __swig_setmethods__["strides"] = _conv1d.Conv1D_strides_set
    __swig_getmethods__["strides"] = _conv1d.Conv1D_strides_get
    if _newclass:
        strides = _swig_property(_conv1d.Conv1D_strides_get, _conv1d.Conv1D_strides_set)
    __swig_setmethods__["kernel_shape"] = _conv1d.Conv1D_kernel_shape_set
    __swig_getmethods__["kernel_shape"] = _conv1d.Conv1D_kernel_shape_get
    if _newclass:
        kernel_shape = _swig_property(_conv1d.Conv1D_kernel_shape_get, _conv1d.Conv1D_kernel_shape_set)
    __swig_setmethods__["weight_shape"] = _conv1d.Conv1D_weight_shape_set
    __swig_getmethods__["weight_shape"] = _conv1d.Conv1D_weight_shape_get
    if _newclass:
        weight_shape = _swig_property(_conv1d.Conv1D_weight_shape_get, _conv1d.Conv1D_weight_shape_set)
    __swig_setmethods__["filters"] = _conv1d.Conv1D_filters_set
    __swig_getmethods__["filters"] = _conv1d.Conv1D_filters_get
    if _newclass:
        filters = _swig_property(_conv1d.Conv1D_filters_get, _conv1d.Conv1D_filters_set)
    __swig_setmethods__["dilation_rate"] = _conv1d.Conv1D_dilation_rate_set
    __swig_getmethods__["dilation_rate"] = _conv1d.Conv1D_dilation_rate_get
    if _newclass:
        dilation_rate = _swig_property(_conv1d.Conv1D_dilation_rate_get, _conv1d.Conv1D_dilation_rate_set)
    __swig_setmethods__["activation"] = _conv1d.Conv1D_activation_set
    __swig_getmethods__["activation"] = _conv1d.Conv1D_activation_get
    if _newclass:
        activation = _swig_property(_conv1d.Conv1D_activation_get, _conv1d.Conv1D_activation_set)
    __swig_setmethods__["padding"] = _conv1d.Conv1D_padding_set
    __swig_getmethods__["padding"] = _conv1d.Conv1D_padding_get
    if _newclass:
        padding = _swig_property(_conv1d.Conv1D_padding_get, _conv1d.Conv1D_padding_set)
    __swig_setmethods__["data_format"] = _conv1d.Conv1D_data_format_set
    __swig_getmethods__["data_format"] = _conv1d.Conv1D_data_format_get
    if _newclass:
        data_format = _swig_property(_conv1d.Conv1D_data_format_get, _conv1d.Conv1D_data_format_set)
    __swig_setmethods__["input_shape"] = _conv1d.Conv1D_input_shape_set
    __swig_getmethods__["input_shape"] = _conv1d.Conv1D_input_shape_get
    if _newclass:
        input_shape = _swig_property(_conv1d.Conv1D_input_shape_get, _conv1d.Conv1D_input_shape_set)
    __swig_setmethods__["output_shape"] = _conv1d.Conv1D_output_shape_set
    __swig_getmethods__["output_shape"] = _conv1d.Conv1D_output_shape_get
    if _newclass:
        output_shape = _swig_property(_conv1d.Conv1D_output_shape_get, _conv1d.Conv1D_output_shape_set)

    def __init__(self):
        this = _conv1d.new_Conv1D()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _conv1d.delete_Conv1D
    __del__ = lambda self: None
Conv1D_swigregister = _conv1d.Conv1D_swigregister
Conv1D_swigregister(Conv1D)


def activate(arg1, arg2, arg3):
    return _conv1d.activate(arg1, arg2, arg3)
activate = _conv1d.activate

def sigmoid(arg1):
    return _conv1d.sigmoid(arg1)
sigmoid = _conv1d.sigmoid

def softplus(arg1):
    return _conv1d.softplus(arg1)
softplus = _conv1d.softplus

def softsign(input):
    return _conv1d.softsign(input)
softsign = _conv1d.softsign

def hard_sigmoid(input):
    return _conv1d.hard_sigmoid(input)
hard_sigmoid = _conv1d.hard_sigmoid

def exponential(input):
    return _conv1d.exponential(input)
exponential = _conv1d.exponential

def relu(input):
    return _conv1d.relu(input)
relu = _conv1d.relu

def hyper_tan(input):
    return _conv1d.hyper_tan(input)
hyper_tan = _conv1d.hyper_tan

def softmax(input, output_shape):
    return _conv1d.softmax(input, output_shape)
softmax = _conv1d.softmax
# This file is compatible with both classic and new-style classes.

cvar = _conv1d.cvar
conv1d_1_W = cvar.conv1d_1_W
conv1d_1_b = cvar.conv1d_1_b
conv1d_2_W = cvar.conv1d_2_W
conv1d_2_b = cvar.conv1d_2_b
dense_1_W = cvar.dense_1_W
dense_1_b = cvar.dense_1_b
dense_2_W = cvar.dense_2_W
dense_2_b = cvar.dense_2_b
dense_3_W = cvar.dense_3_W
dense_3_b = cvar.dense_3_b
dense_4_W = cvar.dense_4_W
dense_4_b = cvar.dense_4_b
dense_5_W = cvar.dense_5_W
dense_5_b = cvar.dense_5_b
dense_6_W = cvar.dense_6_W
dense_6_b = cvar.dense_6_b
dense_7_W = cvar.dense_7_W
dense_7_b = cvar.dense_7_b
dense_8_W = cvar.dense_8_W
dense_8_b = cvar.dense_8_b

